package com.task.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.ToStringSerializer;
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;
import org.mongodb.morphia.annotations.Property;

@Entity(value= "configuration", noClassnameStored = true)
public class ConfigurationDTO {

    @Id
    @Property(value="_id")
    @JsonSerialize(using = ToStringSerializer.class)
    private ObjectId id;

    @JsonProperty("configId")
    @Property(value = "configId")
    private String configId;

    @JsonProperty("description")
    @Property(value = "description")
    private String description;

    @JsonProperty("value")
    @Property(value = "value")
    private String value;

    /**
     * Class constructor
     */
    public ConfigurationDTO() {
        this.id = null;
        this.configId = null;
        this.description = null;
        this.value = null;
    }

    /**
     * Gets the Id generated by Mongo
     * @return id A mongo ObjectId
     */
    public ObjectId getId() {
        return this.id;
    }

    /**
     * Sets the Mongo Id
     * @param id A mongo ObjectId
     */

    public void setId(ObjectId id) {
        this.id = id;
    }

    /**
     * Gets the id corresponding with the name of the configuration variable
     * @return configId a String with the configId name
     */

    public String getConfigId() {
        return this.configId;
    }

    /**
     * Sets the ConfigId
     * @param configId A String with the new configId
     */

    public void setConfigId(String configId) {
        this.configId = configId;
    }

    /**
     * Gets a description of the configuration variable
     * @return description A String with the description
     */

    public String getDescription() {
        return description;
    }

    /**
     * Sets the description of a configuration variable
     * @param description A String with the description
     */

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets the value of the configuration variable
     * @return
     */

    public String getValue() {
        return value;
    }

    /**
     * Sets the value of configuration variables
     * @param value
     */
    public void setValue(String value) {
        this.value = value;
    }
}